home:
   path: /
   controller: App\Infrastructure\Http\Web\Controller\UtilisateurController::index
   methods: [GET, POST]

user_index:
    path: /admin/utilisateur
    controller: App\Infrastructure\Http\Web\Controller\UtilisateurController::usersList
    methods:  [GET, POST]

user_edit_admin_index:
    path: /admin/utilisateur/edit/{id}
    controller: App\Infrastructure\Http\Web\Controller\UtilisateurController::editUserAdmin
    methods: [POST,GET]

user_show_admin_index:
    path: /admin/utilisateur/show/{id}
    controller: App\Infrastructure\Http\Web\Controller\UtilisateurController::showUserAdmin
    methods: [GET]

user_edit_index:
    path: /utilisateur/edit/{id}
    controller: App\Infrastructure\Http\Web\Controller\UtilisateurController::editUser
    methods: [POST, GET]

# Routes for Fonction object
fonction_index:
    path: admin/fonction
    controller: App\Infrastructure\Http\Web\Controller\FonctionController::index
    methods: [GET]

fonction_new:
    path: admin/fonction/new
    controller: App\Infrastructure\Http\Web\Controller\FonctionController::new
    methods: [GET, POST]

# Routes for Role object
role_index:
    path: admin/role
    controller: App\Infrastructure\Http\Web\Controller\RoleController::index
    methods: [GET]

role_new:
    path: admin/role/new
    controller: App\Infrastructure\Http\Web\Controller\RoleController::new
    methods: [GET, POST]

role_edit:
    path: admin/role/edit/{id}
    controller: App\Infrastructure\Http\Web\Controller\RoleController::edit
    methods: [GET, POST]

role_show:
    path: admin/role/show/{id}
    controller: App\Infrastructure\Http\Web\Controller\RoleController::show
    methods: [GET, POST]

# Routes for Category object
category_index:
    path: admin/category
    controller: App\Infrastructure\Http\Web\Controller\CategoryController::index
    methods: [GET]

category_new:
    path: admin/category/new
    controller: App\Infrastructure\Http\Web\Controller\CategoryController::new
    methods: [GET, POST]

category_edit:
    path: admin/category/edit/{id}
    controller: App\Infrastructure\Http\Web\Controller\CategoryController::edit
    methods: [GET, POST]

category_show:
    path: admin/category/show/{id}
    controller: App\Infrastructure\Http\Web\Controller\CategoryController::show
    methods: [GET, POST]

# Routes for Company object
company_index:
    path: company
    controller: App\Infrastructure\Http\Web\Controller\CompanyController::index
    methods: [GET]

company_new:
    path: company/new
    controller: App\Infrastructure\Http\Web\Controller\CompanyController::new
    methods: [GET, POST]

company_edit:
    path: company/edit/{id}
    controller: App\Infrastructure\Http\Web\Controller\CompanyController::edit
    methods: [GET, POST]

company_show:
    path: company/show/{id}
    controller: App\Infrastructure\Http\Web\Controller\CompanyController::show
    methods: [GET, POST]

# Routes for Group object
group_index:
    path: admin/group
    controller: App\Infrastructure\Http\Web\Controller\GroupController::index
    methods: [GET]

group_new:
    path: admin/group/new
    controller: App\Infrastructure\Http\Web\Controller\GroupController::new
    methods: [GET, POST]

group_edit:
    path: admin/group/edit/{id}
    controller: App\Infrastructure\Http\Web\Controller\GroupController::edit
    methods: [GET, POST]

group_show:
    path: admin/group/show/{id}
    controller: App\Infrastructure\Http\Web\Controller\GroupController::show
    methods: [GET, POST]
