doctrine:
    dbal:
        driver: 'pdo_pgsql'
        dbname: sakabay
        user: main
        password: main
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8
        url: '%env(resolve:DATABASE_URL)%'
        schema_filter: ~^(?!temp_)~

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/orm'
                prefix: 'App\Domain\Model'
                alias: App
