version: '2'

services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: sakabay
    ports:
      - "5432:5432"
    volumes:
      - ./sakabay:/var/lib/postgres/data
  redis:
    image: redis:4.0
    ports:
        - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
        - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
  php:
    build: docker/php-fpm
    volumes:
      - ./sakabay:/var/www/sakabay:cached
    ports:
      - "9000:9000"
  nginx:
      build: ./docker/nginx
      ports:
          - "80:80"
      volumes_from:
        - php
      volumes:
          - ./logs/nginx/:/var/log/nginx:cached
  pgadmin:
        image: dpage/pgadmin4
        ports:
            - "82:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: symfony
            PGADMIN_DEFAULT_PASSWORD: symfony
volumes:
  data:
    external: true


