fos_rest:
    serializer:
        serialize_null:  true
    body_listener: true
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
        formats:
            json: true
    param_fetcher_listener:
        enabled: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, 'html' ] }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
    exception:
        enabled: true
        messages:
            'Symfony\Component\HttpKernel\Exception\HttpException': true
