App\Domain\Model\Besoin:
    type: entity
    table: besoin
    repositoryClass: App\Infrastructure\Repository\BesoinRepository
    options:
        comment: Entité représentant un Besoin.

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                comment: Identifiant technique d'un besoin
    fields:
        title:
            type: string
            length: 191
            column: title
            nullable: false
        description:
            type: string
            length: 1000
            column: description
            nullable: false
        dtCreated:
            type: datetime
            gedmo:
                timestampable:
                    on: create
            options:
                default: CURRENT_TIMESTAMP
        dtUpdated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
            options:
                default: CURRENT_TIMESTAMP
    manyToOne:
        category:
            targetEntity: Category
            cascade: [persist]
            inversedBy: besoins
            joinColumn:
                name: id_category
                referencedColumnName: id
                nullable: false
        author:
            targetEntity: Utilisateur
            cascade: [persist]
            inversedBy: besoins
            joinColumn:
                name: id_author
                referencedColumnName: id
                nullable: false
        besoinStatut:
            targetEntity: BesoinStatut
            cascade: [persist]
            inversedBy: besoins
            joinColumn:
                name: id_besoin_statut
                referencedColumnName: id
                nullable: false
        company:
            targetEntity: Company
            cascade: [persist]
            inversedBy: besoins
            joinColumn:
                name: id_company
                referencedColumnName: id
                nullable: true
        companySelected:
            targetEntity: Company
            cascade: [persist]
            inversedBy: besoinSelected
            joinColumn:
                name: id_company_selected
                referencedColumnName: id
                nullable: true
    manyToMany:
        sousCategorys:
            targetEntity: SousCategory
            inversedBy: besoins
            joinTable:
                name: besoin_sous_categories
                joinColumn:
                    id_sous_category:
                        referencedColumnName: id
                inverseJoinColumns:
                    id_besoin:
                        referencedColumnName: id
            nullable: false
    oneToMany:
        answers:
            orderBy: {'requestQuote': 'ASC', 'quote': 'DESC', 'dtCreated': 'DESC'}
            targetEntity: Answer
            orphanRemoval: true
            cascade: [persist]
            mappedBy: besoin
    oneToOne:
        comment:
            targetEntity: Comment
            mappedBy: besoin
            cascade: [persist]
            nullable: true


