App\Domain\Model\City:
    type: entity
    table: city
    options:
        comment: Entité représentant une adresse.

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                comment: Identifiant technique d'un city
    fields:
        name:
            type: string
            length: 191
            column: name
            nullable: false

    uniqueConstraints:
        uniqueGroupCode:
            columns: [name]
    oneToMany:
        companys:
            targetEntity: Company
            orphanRemoval: false
            cascade: [persist]
            mappedBy: city
