App\Domain\Model\CompanySubscription:
    type: entity
    table: company_subscription
    options:
        comment: Entité pour définir la validité de l'abonnement.

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                comment: Identifiant technique de la company_subscription
    fields:
        dtDebut:
            type: datetime
            length: 50
            nullable: true
            column: dt_debut
        dtFin:
            type: datetime
            length: 50
            nullable: true
            column: dt_fin
        stripeId:
            type: string
            length: 100
            column: stripe_id
            nullable: true

    manyToOne:
        subscription:
            targetEntity: Subscription
            cascade: [persist, merge]
            inversedBy: companySubscriptions
            joinColumn:
                name: id_subscription
                referencedColumnName: id
                nullable: false

        company:
            targetEntity: Company
            cascade: [persist, merge]
            inversedBy: companySubscriptions
            joinColumn:
                name: id_company
                referencedColumnName: id
                nullable: false

        subscriptionStatus:
            targetEntity: SubscriptionStatus
            orphanRemoval: true
            cascade: [persist, remove]
            inversedBy: companySubscriptions
            joinColumn:
                name: id_subscription_status
                referencedColumnName: id
                nullable: false
            nullable: false


