App\Domain\Model\ResetPasswordRequest:
    type: entity
    table: reset_password
    repositoryClass: App\Infrastructure\Repository\ResetPasswordRequestRepository
    options:
        comment: Entité représentant un mot de passe oublié.

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                comment: Identifiant technique d'un mot de passe oublié
    fields:
        expiresAt:
            type: datetime
            length: 50
            nullable: true
            column: expires_at
        requestedAt:
            type: datetime
            length: 50
            nullable: true
            column: requested_at
        selector:
            type: string
            length: 20
            nullable: true
            column: selector
        hashedToken:
            type: string
            length: 100
            nullable: true
            column: hashed_token

    manyToOne:
        user:
            targetEntity: Utilisateur
            cascade: [persist]
            inversedBy: reset_password
            joinColumn:
                name: id_utilisateur
                referencedColumnName: id
                nullable: false
