App\Domain\Model\Utilisateur:
    type: entity
    table: utilisateur
    options:
        comment: Entité représentant un user

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                comment: Identifiant technique d'un user
    fields:
        login:
            type: string
            length: 300
            column: login
            nullable: false
        email:
            type: string
            length: 300
            column: email
            nullable: false
        firstName:
            type: string
            length: 300
            column: first_name
            nullable: false
        password:
            type: string
            length: 300
            column: password
            nullable: false
        lastName:
            type: string
            length: 300
            column: last_name
            nullable: false
        imageProfil:
            type: string
            length: 100
            column: image_profil
            nullable: true
        updated:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP

    uniqueConstraints:
        uniqueGroupCode:
            columns: [login, email]
    manyToMany:
        groups:
            targetEntity: Group
            inversedBy: utilisateurs
            joinTable:
                name: utilisateurs_groupes
                joinColumns:
                    id_user:
                        referencedColumnName: id
                inverseJoinColumns:
                    id_group:
                        referencedColumnName: id

