App\Domain\Model\Utilisateur:
    type: entity
    table: utilisateur
    options:
        comment: Entité représentant un user

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                comment: Identifiant technique d'un user
    fields:
        login:
            type: string
            length: 300
            column: login
            nullable: true
        email:
            type: string
            length: 300
            column: email
            nullable: true
        firstName:
            type: string
            length: 300
            column: first_name
            nullable: true
        password:
            type: string
            length: 300
            column: password
            nullable: true
        lastName:
            type: string
            length: 300
            column: last_name
            nullable: true
    manyToMany:
        groups:
            targetEntity: Group
            inversedBy: utilisateurs
            joinTable:
                name: utilisateurs_groupes
                joinColumns:
                    id_user:
                        referencedColumnName: id
                inverseJoinColumns:
                    id_group:
                        referencedColumnName: id
