App\Domain\Model\Utilisateur:
    type: entity
    table: utilisateur
    options:
        comment: Entité représentant un user

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                comment: Identifiant technique d'un user
    fields:
        nom:
            type: string
            length: 100
            column: nom
            nullable: true
        prenom:
            type: string
            length: 200
            column: prenom
            nullable: true
        login:
            type: string
            length: 300
            column: login
            nullable: true
        email:
            type: string
            length: 300
            column: email
            nullable: true
        firstName:
            type: string
            length: 300
            column: first_name
            nullable: true
        password:
            type: string
            length: 300
            column: password
            nullable: true
        lastName:
            type: string
            length: 300
            column: last_name
            nullable: true

